# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CoxFitCpp <- function(lp, status, riskset) {
    .Call('_penalized_CoxFitCpp', PACKAGE = 'penalized', lp, status, riskset)
}

Lasso <- function(beta, lambda, lambda2, positive, X, fit, trace, epsilon, maxiter) {
    .Call('_penalized_Lasso', PACKAGE = 'penalized', beta, lambda, lambda2, positive, X, fit, trace, epsilon, maxiter)
}

StepLasso <- function(beta, lambda, lambda2, positive, X, fit, trace, epsilon, maxiter) {
    .Call('_penalized_StepLasso', PACKAGE = 'penalized', beta, lambda, lambda2, positive, X, fit, trace, epsilon, maxiter)
}

Ridge <- function(beta, eta, Lambda, X, fit, trace, epsilon, maxiter, fitInput) {
    .Call('_penalized_Ridge', PACKAGE = 'penalized', beta, eta, Lambda, X, fit, trace, epsilon, maxiter, fitInput)
}

